name: C++ CI with Docker

on:
  push:
    branches: [ "main", "docker-setup" ]
  pull_request:
    branches: [ "main", "docker-setup" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/lab1-app:${{ github.sha }} .
        docker push ghcr.io/${{ github.repository_owner }}/lab1-app:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull ghcr.io/${{ github.repository_owner }}/lab1-app:${{ github.sha }}

    - name: Run tests inside container
      run: docker run --rm ghcr.io/${{ github.repository_owner }}/lab1-app:${{ github.sha }}
